### ISSUE TITLE
word2vec via gensim?

### ISSUE THREAD

**Issue by timClicks** [JuliaText/TextAnalysis.jl#28]
Would be nice to provide word2vec support within Julia. IMO its natural home would be here.

One way, and hopefully both the easiest and fastest, would be to interface with [`gensim`](http://radimrehurek.com/gensim/) via PyCall rather than to wrap the original C lib.

**Comment by ccsv** [comment]
@timClicks There are some tradeoffs from the C version and the `gensim` version. You can see them in Radim Řehůřek presentation:

https://www.youtube.com/watch?v=vU4TlwZzTfU

The `gensim` version is suppose to be optimize using Cython + BLAS + Sigmoid table for non distributed this is very good better than the C version.

However when you start using multiple threads, the `gensim` version will take up  more memory than the C version, since there is a larger overhead.

The best choice to write the whole thing in Julia and take advantage of the power in distributive programming. But it is a long term thing since it is a lots of work.

**Comment by sambitdash** [comment]
`Word2Vec` should be made native to `TextAnalysis` like LSA and LDA. `Word2Vec` is already available as an independent modules. But the expectation is the whole blob of text should be provided to `Word2Vec`. With the corpus interface there may be a much better interface for `Word2Vec`.

**Comment by aviks** [comment]
Yeah, happy to take PR's to that effect. I generally use Word2Vec separately, but I agree it would be nice to have a combined interface.

**Comment by aviks** [comment]
I think Word2Vec.jl provides the functionality we need. https://github.com/JuliaText/Word2Vec.jl
