### ISSUE TITLE
unknown words lead to error in sentiment analysis

### ISSUE THREAD

**Issue by schottmueller** [JuliaText/TextAnalysis.jl#83]
```
using TextAnalysis
model = TextAnalysis.SentimentAnalyzer()
model(TextAnalysis.Document("some sense and some nonSense"))
```
leads to 
``ERROR: KeyError: key "nonSense" not found``
I am not familiar with sentiment analysis but is it impossible to simply ignore words that do not have a value assigned?

**Comment by aviks** [comment]
I've debated (mostly in my own mind) how to handle this error. On one hand, if the training dictionary is very different from your prediction corpus, you would want to know, since the accuracy would be bad if they are very different. On the other hand, if you are running this in production on user supplied data, you would not want to crash the runtime every time someone mistypes some text.

So not sure what the right answer is. Still thinking about it.

**Comment by schottmueller** [comment]
I agree that one would like to know whether the prediction corpus fits the training data but demanding 100% overlap seems excessive (typos, names numbers etc.). Ideally, the output would be a score and an accuracy measure. A simpler alternative might be a Boolean kwarg to switch between current behavior and a behavior where words outside the training dictionary are ignored. (Unfortunately, I do not understand sentiment analysis well enough to make a pull request.)
